<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:s1="http://moapinterop.org/xsd" xmlns:moap12="http://schemas.xmlmoap.org/wsdl/moap12/" xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://moapinterop.org/" xmlns:s3="http://moapinterop.org/echoheader/" xmlns:moap12enc="http://www.w3.org/2002/06/moap-envelope" xmlns:http="http://schemas.xmlmoap.org/wsdl/http/" xmlns:moapenc="http://schemas.xmlmoap.org/moap/encoding/" xmlns:s2="http://moapinterop.org" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlmoap.org/wsdl/mime/" targetNamespace="http://moapinterop.org/" xmlns="http://schemas.xmlmoap.org/wsdl/">
  <types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://moapinterop.org/">
      <s:import namespace="http://moapinterop.org/xsd" />
      <s:import namespace="http://moapinterop.org/echoheader/" />
      <s:element name="echoVoid">
        <s:complexType />
      </s:element>
      <s:element name="echoVoidResponse">
        <s:complexType />
      </s:element>
      <s:element name="echoInteger">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputInteger" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoIntegerResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoFloat">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputFloat" type="s:float" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoFloatResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s:float" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoString">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputString" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoStringResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoBase64">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputBase64" type="s:base64Binary" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoBase64Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s:base64Binary" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoDate">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputDate" type="s:dateTime" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoDateResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s:dateTime" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoComplexType">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputComplexType" type="s1:moapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoComplexTypeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s1:moapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoIntegerMultiOccurs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputIntegerMultiOccurs" type="s0:ArrayOfInt" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfInt">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="int" type="s:int" />
        </s:sequence>
      </s:complexType>
      <s:element name="echoIntegerMultiOccursResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="unbounded" name="return" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoFloatMultiOccurs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputFloatMultiOccurs" type="s0:ArrayOfFloat" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfFloat">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="float" type="s:float" />
        </s:sequence>
      </s:complexType>
      <s:element name="echoFloatMultiOccursResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="unbounded" name="return" type="s:float" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoStringMultiOccurs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputStringMultiOccurs" type="s0:ArrayOfString" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfString">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="echoStringMultiOccursResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="unbounded" name="return" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoComplexTypeMultiOccurs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputComplexTypeMultiOccurs" type="s1:ArrayOfmoapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="moapComplexType" nillable="true" type="s1:moapComplexType" />
      <s:element name="echoComplexTypeMultiOccursResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="unbounded" name="return" type="s1:moapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoDecimal">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputDecimal" type="s:decimal" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoDecimalResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s:decimal" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoBoolean">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputBoolean" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoBooleanResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoHexBinary">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputHexBinary" type="s:hexBinary" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoHexBinaryResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s:hexBinary" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoComplexTypeAsSimpleTypes">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputComplexType" type="s1:moapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoComplexTypeAsSimpleTypesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="outputString" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="outputInteger" type="s:int" />
            <s:element minOccurs="1" maxOccurs="1" name="outputFloat" type="s:float" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoSimpleTypesAsComplexType">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputString" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="inputInteger" type="s:int" />
            <s:element minOccurs="1" maxOccurs="1" name="inputFloat" type="s:float" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoSimpleTypesAsComplexTypeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s1:moapComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoNestedComplexType">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputComplexType" type="s1:moapComplexTypeComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoNestedComplexTypeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s1:moapComplexTypeComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoNestedMultiOccurs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputComplexType" type="s1:moapMultiOccursComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoNestedMultiOccursResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s1:moapMultiOccursComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoChoice">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputChoice" type="s1:ChoiceComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoChoiceResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" type="s1:ChoiceComplexType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoEnum">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="inputEnum" type="s1:Enum" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoEnumResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="return" type="s1:Enum" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoAnyType">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputAnyType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoAnyTypeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoAnyElement">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputAny">
              <s:complexType>
                <s:sequence>
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoAnyElementResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="return">
              <s:complexType>
                <s:sequence>
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="echoVoidmoapHeaderResponse">
        <s:complexType />
      </s:element>
      <s:element name="echoMeComplexTypeRequest" type="s3:echoMeComplexTypeRequest" />
      <s:element name="echoMeStringRequest" type="s3:echoMeStringRequest" />
      <s:element name="echoMeComplexTypeResponse" type="s3:echoMeComplexTypeResponse" />
      <s:element name="echoMeStringResponse" type="s3:echoMeStringResponse" />
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://moapinterop.org/xsd">
      <s:import namespace="http://moapinterop.org/" />
      <s:complexType name="moapComplexType">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="varInt" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="varFloat" type="s:float" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfmoapComplexType">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" ref="s0:moapComplexType" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="moapComplexTypeComplexType">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="varInt" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="varFloat" type="s:float" />
          <s:element minOccurs="0" maxOccurs="1" name="varComplexType" type="s1:moapComplexType" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="moapMultiOccursComplexType">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="varInt" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="varFloat" type="s:float" />
          <s:element minOccurs="0" maxOccurs="1" name="varMultiOccurs" type="s1:ArrayOfString" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfString">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ChoiceComplexType">
        <s:sequence>
          <s:choice minOccurs="1" maxOccurs="1">
            <s:element minOccurs="0" maxOccurs="1" name="name0" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="name1" type="s:string" />
          </s:choice>
        </s:sequence>
      </s:complexType>
      <s:simpleType name="Enum">
        <s:restriction base="s:string">
          <s:enumeration value="BitOne" />
          <s:enumeration value="BitTwo" />
          <s:enumeration value="BitThree" />
          <s:enumeration value="BitFour" />
          <s:enumeration value="BitFive" />
        </s:restriction>
      </s:simpleType>
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://moapinterop.org">
      <s:element name="echoVoidmoapHeader">
        <s:complexType />
      </s:element>
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://moapinterop.org/echoheader/">
      <s:complexType name="echoMeComplexTypeRequest">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="varInt" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="varFloat" type="s:float" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="echoMeStringRequest">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="echoMeComplexTypeResponse">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="varInt" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="varFloat" type="s:float" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="echoMeStringResponse">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="varString" type="s:string" />
        </s:sequence>
      </s:complexType>
    </s:schema>
  </types>
  <message name="echoVoidmoapIn">
    <part name="parameters" element="s0:echoVoid" />
  </message>
  <message name="echoVoidmoapOut">
    <part name="parameters" element="s0:echoVoidResponse" />
  </message>
  <message name="echoIntegermoapIn">
    <part name="parameters" element="s0:echoInteger" />
  </message>
  <message name="echoIntegermoapOut">
    <part name="parameters" element="s0:echoIntegerResponse" />
  </message>
  <message name="echoFloatmoapIn">
    <part name="parameters" element="s0:echoFloat" />
  </message>
  <message name="echoFloatmoapOut">
    <part name="parameters" element="s0:echoFloatResponse" />
  </message>
  <message name="echoStringmoapIn">
    <part name="parameters" element="s0:echoString" />
  </message>
  <message name="echoStringmoapOut">
    <part name="parameters" element="s0:echoStringResponse" />
  </message>
  <message name="echoBase64moapIn">
    <part name="parameters" element="s0:echoBase64" />
  </message>
  <message name="echoBase64moapOut">
    <part name="parameters" element="s0:echoBase64Response" />
  </message>
  <message name="echoDatemoapIn">
    <part name="parameters" element="s0:echoDate" />
  </message>
  <message name="echoDatemoapOut">
    <part name="parameters" element="s0:echoDateResponse" />
  </message>
  <message name="echoComplexTypemoapIn">
    <part name="parameters" element="s0:echoComplexType" />
  </message>
  <message name="echoComplexTypemoapOut">
    <part name="parameters" element="s0:echoComplexTypeResponse" />
  </message>
  <message name="echoIntegerMultiOccursmoapIn">
    <part name="parameters" element="s0:echoIntegerMultiOccurs" />
  </message>
  <message name="echoIntegerMultiOccursmoapOut">
    <part name="parameters" element="s0:echoIntegerMultiOccursResponse" />
  </message>
  <message name="echoFloatMultiOccursmoapIn">
    <part name="parameters" element="s0:echoFloatMultiOccurs" />
  </message>
  <message name="echoFloatMultiOccursmoapOut">
    <part name="parameters" element="s0:echoFloatMultiOccursResponse" />
  </message>
  <message name="echoStringMultiOccursmoapIn">
    <part name="parameters" element="s0:echoStringMultiOccurs" />
  </message>
  <message name="echoStringMultiOccursmoapOut">
    <part name="parameters" element="s0:echoStringMultiOccursResponse" />
  </message>
  <message name="echoComplexTypeMultiOccursmoapIn">
    <part name="parameters" element="s0:echoComplexTypeMultiOccurs" />
  </message>
  <message name="echoComplexTypeMultiOccursmoapOut">
    <part name="parameters" element="s0:echoComplexTypeMultiOccursResponse" />
  </message>
  <message name="echoDecimalmoapIn">
    <part name="parameters" element="s0:echoDecimal" />
  </message>
  <message name="echoDecimalmoapOut">
    <part name="parameters" element="s0:echoDecimalResponse" />
  </message>
  <message name="echoBooleanmoapIn">
    <part name="parameters" element="s0:echoBoolean" />
  </message>
  <message name="echoBooleanmoapOut">
    <part name="parameters" element="s0:echoBooleanResponse" />
  </message>
  <message name="echoHexBinarymoapIn">
    <part name="parameters" element="s0:echoHexBinary" />
  </message>
  <message name="echoHexBinarymoapOut">
    <part name="parameters" element="s0:echoHexBinaryResponse" />
  </message>
  <message name="echoComplexTypeAsSimpleTypesmoapIn">
    <part name="parameters" element="s0:echoComplexTypeAsSimpleTypes" />
  </message>
  <message name="echoComplexTypeAsSimpleTypesmoapOut">
    <part name="parameters" element="s0:echoComplexTypeAsSimpleTypesResponse" />
  </message>
  <message name="echoSimpleTypesAsComplexTypemoapIn">
    <part name="parameters" element="s0:echoSimpleTypesAsComplexType" />
  </message>
  <message name="echoSimpleTypesAsComplexTypemoapOut">
    <part name="parameters" element="s0:echoSimpleTypesAsComplexTypeResponse" />
  </message>
  <message name="echoNestedComplexTypemoapIn">
    <part name="parameters" element="s0:echoNestedComplexType" />
  </message>
  <message name="echoNestedComplexTypemoapOut">
    <part name="parameters" element="s0:echoNestedComplexTypeResponse" />
  </message>
  <message name="echoNestedMultiOccursmoapIn">
    <part name="parameters" element="s0:echoNestedMultiOccurs" />
  </message>
  <message name="echoNestedMultiOccursmoapOut">
    <part name="parameters" element="s0:echoNestedMultiOccursResponse" />
  </message>
  <message name="echoChoicemoapIn">
    <part name="parameters" element="s0:echoChoice" />
  </message>
  <message name="echoChoicemoapOut">
    <part name="parameters" element="s0:echoChoiceResponse" />
  </message>
  <message name="echoEnummoapIn">
    <part name="parameters" element="s0:echoEnum" />
  </message>
  <message name="echoEnummoapOut">
    <part name="parameters" element="s0:echoEnumResponse" />
  </message>
  <message name="echoAnyTypemoapIn">
    <part name="parameters" element="s0:echoAnyType" />
  </message>
  <message name="echoAnyTypemoapOut">
    <part name="parameters" element="s0:echoAnyTypeResponse" />
  </message>
  <message name="echoAnyElementmoapIn">
    <part name="parameters" element="s0:echoAnyElement" />
  </message>
  <message name="echoAnyElementmoapOut">
    <part name="parameters" element="s0:echoAnyElementResponse" />
  </message>
  <message name="echoVoidmoapHeadermoapIn">
    <part name="parameters" element="s2:echoVoidmoapHeader" />
  </message>
  <message name="echoVoidmoapHeadermoapOut">
    <part name="parameters" element="s0:echoVoidmoapHeaderResponse" />
  </message>
  <message name="echoVoidmoapHeaderechoMeComplexTypeRequest">
    <part name="echoMeComplexTypeRequest" element="s0:echoMeComplexTypeRequest" />
  </message>
  <message name="echoVoidmoapHeaderechoMeComplexTypeResponse">
    <part name="echoMeComplexTypeResponse" element="s0:echoMeComplexTypeResponse" />
  </message>
  <message name="echoVoidmoapHeaderechoMeStringRequest">
    <part name="echoMeStringRequest" element="s0:echoMeStringRequest" />
  </message>
  <message name="echoVoidmoapHeaderechoMeStringResponse">
    <part name="echoMeStringResponse" element="s0:echoMeStringResponse" />
  </message>
  <portType name="Round4XSDTestmoap">
    <operation name="echoVoid">
      <input message="s0:echoVoidmoapIn" />
      <output message="s0:echoVoidmoapOut" />
    </operation>
    <operation name="echoInteger">
      <input message="s0:echoIntegermoapIn" />
      <output message="s0:echoIntegermoapOut" />
    </operation>
    <operation name="echoFloat">
      <input message="s0:echoFloatmoapIn" />
      <output message="s0:echoFloatmoapOut" />
    </operation>
    <operation name="echoString">
      <input message="s0:echoStringmoapIn" />
      <output message="s0:echoStringmoapOut" />
    </operation>
    <operation name="echoBase64">
      <input message="s0:echoBase64moapIn" />
      <output message="s0:echoBase64moapOut" />
    </operation>
    <operation name="echoDate">
      <input message="s0:echoDatemoapIn" />
      <output message="s0:echoDatemoapOut" />
    </operation>
    <operation name="echoComplexType">
      <input message="s0:echoComplexTypemoapIn" />
      <output message="s0:echoComplexTypemoapOut" />
    </operation>
    <operation name="echoIntegerMultiOccurs">
      <input message="s0:echoIntegerMultiOccursmoapIn" />
      <output message="s0:echoIntegerMultiOccursmoapOut" />
    </operation>
    <operation name="echoFloatMultiOccurs">
      <input message="s0:echoFloatMultiOccursmoapIn" />
      <output message="s0:echoFloatMultiOccursmoapOut" />
    </operation>
    <operation name="echoStringMultiOccurs">
      <input message="s0:echoStringMultiOccursmoapIn" />
      <output message="s0:echoStringMultiOccursmoapOut" />
    </operation>
    <operation name="echoComplexTypeMultiOccurs">
      <input message="s0:echoComplexTypeMultiOccursmoapIn" />
      <output message="s0:echoComplexTypeMultiOccursmoapOut" />
    </operation>
    <operation name="echoDecimal">
      <input message="s0:echoDecimalmoapIn" />
      <output message="s0:echoDecimalmoapOut" />
    </operation>
    <operation name="echoBoolean">
      <input message="s0:echoBooleanmoapIn" />
      <output message="s0:echoBooleanmoapOut" />
    </operation>
    <operation name="echoHexBinary">
      <input message="s0:echoHexBinarymoapIn" />
      <output message="s0:echoHexBinarymoapOut" />
    </operation>
    <operation name="echoComplexTypeAsSimpleTypes">
      <input message="s0:echoComplexTypeAsSimpleTypesmoapIn" />
      <output message="s0:echoComplexTypeAsSimpleTypesmoapOut" />
    </operation>
    <operation name="echoSimpleTypesAsComplexType">
      <input message="s0:echoSimpleTypesAsComplexTypemoapIn" />
      <output message="s0:echoSimpleTypesAsComplexTypemoapOut" />
    </operation>
    <operation name="echoNestedComplexType">
      <input message="s0:echoNestedComplexTypemoapIn" />
      <output message="s0:echoNestedComplexTypemoapOut" />
    </operation>
    <operation name="echoNestedMultiOccurs">
      <input message="s0:echoNestedMultiOccursmoapIn" />
      <output message="s0:echoNestedMultiOccursmoapOut" />
    </operation>
    <operation name="echoChoice">
      <input message="s0:echoChoicemoapIn" />
      <output message="s0:echoChoicemoapOut" />
    </operation>
    <operation name="echoEnum">
      <input message="s0:echoEnummoapIn" />
      <output message="s0:echoEnummoapOut" />
    </operation>
    <operation name="echoAnyType">
      <input message="s0:echoAnyTypemoapIn" />
      <output message="s0:echoAnyTypemoapOut" />
    </operation>
    <operation name="echoAnyElement">
      <input message="s0:echoAnyElementmoapIn" />
      <output message="s0:echoAnyElementmoapOut" />
    </operation>
    <operation name="echoVoidmoapHeader">
      <input message="s0:echoVoidmoapHeadermoapIn" />
      <output message="s0:echoVoidmoapHeadermoapOut" />
    </operation>
  </portType>
  <binding name="Round4XSDTestmoap" type="s0:Round4XSDTestmoap">
    <moap:binding transport="http://schemas.xmlmoap.org/moap/http" style="document" />
    <operation name="echoVoid">
      <moap:operation moapAction="http://moapinterop.org/echoVoid" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoInteger">
      <moap:operation moapAction="http://moapinterop.org/echoInteger" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoFloat">
      <moap:operation moapAction="http://moapinterop.org/echoFloat" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoString">
      <moap:operation moapAction="http://moapinterop.org/echoString" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoBase64">
      <moap:operation moapAction="http://moapinterop.org/echoBase64" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoDate">
      <moap:operation moapAction="http://moapinterop.org/echoDate" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexType">
      <moap:operation moapAction="http://moapinterop.org/echoComplexType" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoIntegerMultiOccurs">
      <moap:operation moapAction="http://moapinterop.org/echoIntegerMultiOccurs" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoFloatMultiOccurs">
      <moap:operation moapAction="http://moapinterop.org/echoFloatMultiOccurs" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoStringMultiOccurs">
      <moap:operation moapAction="http://moapinterop.org/echoStringMultiOccurs" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexTypeMultiOccurs">
      <moap:operation moapAction="http://moapinterop.org/echoComplexTypeMultiOccurs" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoDecimal">
      <moap:operation moapAction="http://moapinterop.org/echoDecimal" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoBoolean">
      <moap:operation moapAction="http://moapinterop.org/echoBoolean" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoHexBinary">
      <moap:operation moapAction="http://moapinterop.org/echoHexBinary" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexTypeAsSimpleTypes">
      <moap:operation moapAction="http://moapinterop.org/echoComplexTypeAsSimpleTypes" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoSimpleTypesAsComplexType">
      <moap:operation moapAction="http://moapinterop.org/echoSimpleTypesAsComplexType" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoNestedComplexType">
      <moap:operation moapAction="http://moapinterop.org/echoNestedComplexType" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoNestedMultiOccurs">
      <moap:operation moapAction="http://moapinterop.org/echoNestedMultiOccurs" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoChoice">
      <moap:operation moapAction="http://moapinterop.org/echoChoice" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoEnum">
      <moap:operation moapAction="http://moapinterop.org/echoEnum" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoAnyType">
      <moap:operation moapAction="http://moapinterop.org/echoAnyType" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoAnyElement">
      <moap:operation moapAction="http://moapinterop.org/echoAnyElement" style="document" />
      <input>
        <moap:body use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
      </output>
    </operation>
    <operation name="echoVoidmoapHeader">
      <moap:operation moapAction="http://moapinterop.org" style="document" />
      <input>
        <moap:body use="literal" />
        <moap:header message="s0:echoVoidmoapHeaderechoMeComplexTypeRequest" part="echoMeComplexTypeRequest" use="literal" />
        <moap:header message="s0:echoVoidmoapHeaderechoMeStringRequest" part="echoMeStringRequest" use="literal" />
      </input>
      <output>
        <moap:body use="literal" />
        <moap:header message="s0:echoVoidmoapHeaderechoMeComplexTypeResponse" part="echoMeComplexTypeResponse" use="literal" />
        <moap:header message="s0:echoVoidmoapHeaderechoMeStringResponse" part="echoMeStringResponse" use="literal" />
      </output>
    </operation>
  </binding>
  <binding name="Round4XSDTestmoap12" type="s0:Round4XSDTestmoap">
    <moap12:binding transport="http://schemas.xmlmoap.org/moap/http" style="document" />
    <operation name="echoVoid">
      <moap12:operation moapAction="http://moapinterop.org/echoVoid" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoInteger">
      <moap12:operation moapAction="http://moapinterop.org/echoInteger" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoFloat">
      <moap12:operation moapAction="http://moapinterop.org/echoFloat" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoString">
      <moap12:operation moapAction="http://moapinterop.org/echoString" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoBase64">
      <moap12:operation moapAction="http://moapinterop.org/echoBase64" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoDate">
      <moap12:operation moapAction="http://moapinterop.org/echoDate" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexType">
      <moap12:operation moapAction="http://moapinterop.org/echoComplexType" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoIntegerMultiOccurs">
      <moap12:operation moapAction="http://moapinterop.org/echoIntegerMultiOccurs" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoFloatMultiOccurs">
      <moap12:operation moapAction="http://moapinterop.org/echoFloatMultiOccurs" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoStringMultiOccurs">
      <moap12:operation moapAction="http://moapinterop.org/echoStringMultiOccurs" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexTypeMultiOccurs">
      <moap12:operation moapAction="http://moapinterop.org/echoComplexTypeMultiOccurs" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoDecimal">
      <moap12:operation moapAction="http://moapinterop.org/echoDecimal" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoBoolean">
      <moap12:operation moapAction="http://moapinterop.org/echoBoolean" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoHexBinary">
      <moap12:operation moapAction="http://moapinterop.org/echoHexBinary" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoComplexTypeAsSimpleTypes">
      <moap12:operation moapAction="http://moapinterop.org/echoComplexTypeAsSimpleTypes" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoSimpleTypesAsComplexType">
      <moap12:operation moapAction="http://moapinterop.org/echoSimpleTypesAsComplexType" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoNestedComplexType">
      <moap12:operation moapAction="http://moapinterop.org/echoNestedComplexType" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoNestedMultiOccurs">
      <moap12:operation moapAction="http://moapinterop.org/echoNestedMultiOccurs" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoChoice">
      <moap12:operation moapAction="http://moapinterop.org/echoChoice" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoEnum">
      <moap12:operation moapAction="http://moapinterop.org/echoEnum" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoAnyType">
      <moap12:operation moapAction="http://moapinterop.org/echoAnyType" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoAnyElement">
      <moap12:operation moapAction="http://moapinterop.org/echoAnyElement" style="document" />
      <input>
        <moap12:body use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
      </output>
    </operation>
    <operation name="echoVoidmoapHeader">
      <moap12:operation moapAction="http://moapinterop.org" style="document" />
      <input>
        <moap12:body use="literal" />
        <moap12:header message="s0:echoVoidmoapHeaderechoMeComplexTypeRequest" part="echoMeComplexTypeRequest" use="literal" />
        <moap12:header message="s0:echoVoidmoapHeaderechoMeStringRequest" part="echoMeStringRequest" use="literal" />
      </input>
      <output>
        <moap12:body use="literal" />
        <moap12:header message="s0:echoVoidmoapHeaderechoMeComplexTypeResponse" part="echoMeComplexTypeResponse" use="literal" />
        <moap12:header message="s0:echoVoidmoapHeaderechoMeStringResponse" part="echoMeStringResponse" use="literal" />
      </output>
    </operation>
  </binding>
  <service name="Round4XSDTest">
    <documentation>These operations implement DOC/LIT moap operations, for interop testing. Please email johnko@microsoft.com with any questions/coments.</documentation>
    <port name="Round4XSDTestmoap" binding="s0:Round4XSDTestmoap">
      <moap:address location="test://" />
    </port>
    <port name="Round4XSDTestmoap12" binding="s0:Round4XSDTestmoap12">
      <moap12:address location="http://msmoapinterop.org/asmx/xsd/round4xsd.asmx" />
    </port>
  </service>
</definitions>