<?xml version="1.0"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop.org/definitions/" 
		xmlns:wsdlns="http://moapinterop.org/definitions/" 
		xmlns:typens="http://moapinterop.org/xsd" 
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<import location="import2B.xsd" namespace="http://moapinterop.org/xsd" />
	<message name='Server.echoStruct'>
    		<part name='inputStruct' type='typens:moapStruct'/>
  	</message>
  	<message name='Server.echoStructResponse'>
    		<part name='Result' type='typens:moapStruct'/>
  	</message>

	<portType name="moapInteropImport2PortType">
		<operation name='echoStruct' parameterOrder='inputStruct'>
    			  <input message='wsdlns:Server.echoStruct' />
      			  <output message='wsdlns:Server.echoStructResponse' />
		</operation>
	</portType>	
</definitions>
