<?xml version="1.0"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop.org/definitions/" 
		xmlns:wsdlns="http://moapinterop.org/definitions/" 
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<types/>
	<message name="echoStringRequest">
		<part name="x" type="xsd:string"/>
	</message>
	<message name="echoStringResponse">
		<part name="Result" type="xsd:string"/>
	</message>
	<portType name="moapInteropImport1PortType">
		<operation name="echoString" parameterOrder="x">
			<input message="wsdlns:echoStringRequest"/>
			<output message="wsdlns:echoStringResponse"/>
		</operation>
	</portType>	
</definitions>
