<?xml version="1.0" encoding="UTF-8"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop.org/" 
		xmlns:wsdlns1="http://moapinterop.org/definitions/" 
		xmlns:wsdlns="http://moapinterop.org/"
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<import location="imported/import1B.wsdl" namespace="http://moapinterop.org/definitions/" /> 

	<binding name="moapInteropImport1Binding" type="wsdlns1:moapInteropImport1PortType">
		<moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="echoString">
			<moap:operation moapAction="http://moapinterop.org/"/>
			<input>
				<moap:body use="encoded" namespace="http://moapinterop/echoString/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://moapinterop/echoStringResponse/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Import1">
		<port name="moapInteropImport1Port" binding="wsdlns:moapInteropImport1Binding">
			<moap:address location="round3_groupD_import1.inc"/>
		</port>
	</service>
</definitions>
