<?xml version="1.0" encoding="UTF-8"?>
<definitions name="moapInteropCompound" 
		targetNamespace="http://moapinterop.org/" 
		xmlns:wsdlns="http://moapinterop.org/" 
		xmlns:typens="http://moapinterop.org/xsd"
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<types>
		<schema targetNamespace="http://moapinterop.org/xsd" 
		xmlns="http://www.w3.org/2001/XMLSchema" 
		elementFormDefault="qualified"
		>	
			<complexType name="Person">
				<sequence>
					<element minOccurs="1" maxOccurs="1" name="Age" type="double"/>
					<element minOccurs="1" maxOccurs="1" name="ID" type="xsd:float"/>					
				</sequence>
				<attribute name="Name" type="string"/>
				<attribute name="Male" type="boolean"/>
			</complexType>
			<element name="x_Person" type="typens:Person"/>	
			<element name="result_Person" type="typens:Person"/>
			
			<complexType name="Document">
			<simpleContent>
			 <extension base="string">
			   <xsd:attribute name ="ID" type="string"/>
			 </extension>
			</simpleContent>
			</complexType>	
			<element name="x_Document" type="typens:Document"/>	
			<element name="result_Document" type="typens:Document"/>	
		</schema>
	</types>
	<message name="echoPerson">
		<part name="x" element="typens:x_Person"/>
	</message>
	<message name="echoPersonResponse">
		<part name="Result" element="typens:result_Person"/>
	</message>
	<message name="echoDocument">
		<part name="x" element="typens:x_Document"/>
	</message>
	<message name="echoDocumentResponse">
		<part name="Result" element="typens:result_Document"/>
	</message>
	<portType name="moapInteropCompound1PortType">
		<operation name="echoPerson" parameterOrder="x">
			<input message="wsdlns:echoPerson"/>
			<output message="wsdlns:echoPersonResponse"/>
		</operation>
		<operation name="echoDocument" parameterOrder="x">
			<input message="wsdlns:echoDocument"/>
			<output message="wsdlns:echoDocumentResponse"/>
		</operation>
	</portType>
	<binding name="moapInteropCompound1Binding" type="wsdlns:moapInteropCompound1PortType">
		<moap:binding style="document" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="echoPerson">
			<moap:operation moapAction="http://moapinterop/echoPerson"/>
			<input>
				<moap:body use="literal"/>
			</input>
			<output>
				<moap:body use="literal"/>
			</output>
		</operation>
		<operation name="echoDocument">
			<moap:operation moapAction="http://moapinterop/echoDocument"/>
			<input>
				<moap:body use="literal"/>
			</input>
			<output>
				<moap:body use="literal"/>
			</output>
		</operation>

	</binding>
	<service name="Compound1">
		<port name="moapInteropCompound1Port" binding="wsdlns:moapInteropCompound1Binding">
			<moap:address location="round3_groupD_compound1.inc"/>
		</port>
	</service>
</definitions>
