<?xml version="1.0" encoding="UTF-8"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop.org/main/" 
		xmlns:wsdlns1="http://moapinterop.org/definitions/"  
		xmlns:wsdlns="http://moapinterop.org/main/"  
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 		
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<import location="imported/import2B.wsdl" namespace="http://moapinterop.org/definitions/" /> 

	<binding name="moapInteropImport2Binding" type="wsdlns1:moapInteropImport2PortType">
		<moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="echoStruct">
			<moap:operation moapAction="http://moapinterop.org/"/>
			<input>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Import2">
		<port name="moapInteropImport2Port" binding="wsdlns:moapInteropImport2Binding">
			<moap:address location="round3_groupD_import2.inc"/>
		</port>
	</service>
</definitions>
