<?xml version="1.0" encoding="UTF-8"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop.org/main2/" 
		xmlns:wsdlns="http://moapinterop.org/main2/"  
		xmlns:impns="http://moapinterop.org/definitions/"  
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 		
		xmlns:typens2="http://moapinterop.org/xsd2" 		
		xmlns:typens="http://moapinterop.org/xsd"
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	
	<import namespace = "http://moapinterop.org/xsd" location = "round3_groupD_import2.wsdl"/>
	<import namespace = "http://moapinterop.org/definitions/" location = "round3_groupD_import2.wsdl"/>
	
	<types>
	<schema targetNamespace='http://moapinterop.org/xsd2'
	      xmlns='http://www.w3.org/2001/XMLSchema'  
	      xmlns:moap-ENC='http://schemas.xmlmoap.org/moap/encoding/'      
	      xmlns:wsdl = "http://schemas.xmlmoap.org/wsdl/"		    
	      elementFormDefault='unqualified'>
	      <import namespace = "http://schemas.xmlmoap.org/moap/encoding/"/>
	      <import namespace = "http://moapinterop.org/xsd"/>	
	      <complexType  name ='ArrayOfmoapStruct'>
	        <complexContent>
        	  <restriction base='moap-ENC:Array'>
            		<attribute ref='moap-ENC:arrayType' wsdl:arrayType='typens:moapStruct[]'/>
	          </restriction>
        	</complexContent>
	      </complexType>
	</schema>
	</types>

	<message name='Server.echoStructArray'>
    		<part name='inputArray' type='typens2:ArrayOfmoapStruct'/>
  	</message>
  	<message name='Server.echoStructArrayResponse'>
    		<part name='Result' type='typens2:ArrayOfmoapStruct'/>
  	</message>

	<portType name="moapInteropImport3PortType">
		<operation name='echoStruct' parameterOrder='inputStruct'>
    			  <input message='impns:Server.echoStruct' />
      			  <output message='impns:Server.echoStructResponse' />
		</operation>
		<operation name='echoStructArray' parameterOrder='inputArray'>
    			  <input message='wsdlns:Server.echoStructArray' />
      			  <output message='wsdlns:Server.echoStructArrayResponse' />
		</operation>
	</portType>	

	<binding name="moapInteropImport3Binding" type="wsdlns:moapInteropImport3PortType">
		<moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="echoStruct">
			<moap:operation moapAction="http://moapinterop.org/"/>
			<input>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
		<operation name="echoStructArray">
			<moap:operation moapAction="http://moapinterop.org/"/>
			<input>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Import3">
		<port name="moapInteropImport3Port" binding="wsdlns:moapInteropImport3Binding">
			<moap:address location="round3_groupD_import3.inc"/>
		</port>
	</service>
</definitions>
