<?xml version="1.0" encoding="UTF-8"?>
<definitions name="moapInterop" targetNamespace="http://moapinterop/" 
		xmlns:wsdlns="http://moapinterop/" 
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns="http://schemas.xmlmoap.org/wsdl/">
	<types/>
	<message name="echoStringRequest">
		<part name="a" type="xsd:string"/>
	</message>
	<message name="echoStringResponse">
		<part name="Result" type="xsd:string"/>
	</message>
	<portType name="moapInteropEmptySAPortType">
		<operation name="echoString" parameterOrder="a">
			<input message="wsdlns:echoStringRequest"/>
			<output message="wsdlns:echoStringResponse"/>
		</operation>
	</portType>
	<binding name="moapInteropEmptySABinding" type="wsdlns:moapInteropEmptySAPortType">
		<moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="echoString">
			<moap:operation moapAction=""/>
			<input>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://moapinterop/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="EmptySA">
		<port name="moapInteropEmptySAPort" binding="wsdlns:moapInteropEmptySABinding">
			<moap:address location="round3_groupD_emptysa.inc"/>
		</port>
	</service>
</definitions>
