<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlmoap.org/wsdl/http/" xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:moapenc="http://schemas.xmlmoap.org/moap/encoding/" xmlns:tns="http://tempuri.org/PRWebServ/getOtherInformation" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlmoap.org/wsdl/mime/" targetNamespace="http://tempuri.org/PRWebServ/getOtherInformation" xmlns:wsdl="http://schemas.xmlmoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/PRWebServ/getOtherInformation">
      <s:import namespace="http://www.w3.org/2001/XMLSchema" />
      <s:element name="getContinentList">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="AFFILIATE_ID" type="s:int" />
            <s:element minOccurs="0" maxOccurs="1" name="PASSWORD" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="getContinentListResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="getContinentListResult">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="getContinentListmoapIn">
    <wsdl:part name="parameters" element="tns:getContinentList" />
  </wsdl:message>
  <wsdl:message name="getContinentListmoapOut">
    <wsdl:part name="parameters" element="tns:getContinentListResponse" />
  </wsdl:message>
  <wsdl:portType name="getOtherInformationmoap">
    <wsdl:operation name="getContinentList">
      <wsdl:input message="tns:getContinentListmoapIn" />
      <wsdl:output message="tns:getContinentListmoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="getOtherInformationmoap" type="tns:getOtherInformationmoap">
    <moap:binding transport="http://schemas.xmlmoap.org/moap/http" style="document" />
    <wsdl:operation name="getContinentList">
      <moap:operation moapAction="http://tempuri.org/PRWebServ/getOtherInformation/getContinentList" style="document" />
      <wsdl:input>
        <moap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <moap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="getOtherInformation">
    <wsdl:port name="getOtherInformationmoap" binding="tns:getOtherInformationmoap">
      <moap:address location="http://www.precisionreservations.com/PRWebServ/getOtherInformation.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>