<?xml version="1.0" encoding="utf-8"?>
<definitions name="InteropTest"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:moap-ENC="http://schemas.xmlmoap.org/moap/encoding/"
    xmlns:tns="http://test-uri/"
    xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/"
    xmlns:wsdl="http://schemas.xmlmoap.org/wsdl/"
    xmlns="http://schemas.xmlmoap.org/wsdl/"
    targetNamespace="http://test-uri/">
  <types>
  <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://test-uri/">
   <xsd:import namespace="http://schemas.xmlmoap.org/moap/encoding/" />
   <xsd:import namespace="http://schemas.xmlmoap.org/wsdl/" />
	 <complexType name="testType">
		<sequence>
			<element name="a" type="string"/>
			<element name="b" type="string"/>
		</sequence>
		<attribute name="c" type="string"/>
	 </complexType>
  </schema>
  </types>
  <message name="testMessage">
  	<part name="testParam" type="tns:testType"/>
  </message>
	<portType name="testPortType">
		<operation name="test">
			<input message="testMessage"/>
			<output message="testMessage"/>
		</operation>
	</portType>
	<binding name="testBinding" type="testPortType">
		<moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http"/>
		<operation name="test">
			<moap:operation moapAction="#test" style="rpc"/>
			<input>
				<moap:body use="encoded" namespace="http://test-uri/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</input>
			<output>
				<moap:body use="encoded" namespace="http://test-uri/" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="testService">
   <port name="testPort" binding="tns:testBinding">
     <moap:address location="test://" /> 
   </port>
 </service>
</definitions>
