<?xml version="1.0" encoding="utf-8"?>
<definitions name="shoppingcart"
 xmlns="http://schemas.xmlmoap.org/wsdl/"
 xmlns:tns="urn:test.moapserver#"
targetNamespace="urn:test.moapserver#"
 xmlns:wsdl="http://schemas.xmlmoap.org/wsdl/"
 xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/"
 xmlns:moapenc="http://schemas.xmlmoap.org/moap/encoding/"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 xmlns:types="urn:test.moapserver.types#">

 <!-- all datatypes will be imported to namespace types: -->
 <types>
         <xs:schema targetNamespace="urn:test.moapserver.types#">
                 <xs:complexType name="ThingWithParent">
        <xs:all>
         <xs:element name="id" type="xs:string"/>
         <xs:element name="parent" type="types:ThingWithParent"/>
         <xs:element name="children" type="types:ArrayOfThingWithParent"/>
        </xs:all>
       </xs:complexType>
 <xs:complexType name="ArrayOfThingWithParent">
  <xs:complexContent>
   <xs:restriction base="moapenc:Array">
      <xs:attribute ref="moapenc:arrayType"
        wsdl:arrayType="tns:ThingWithParent[]"/>
   </xs:restriction>
  </xs:complexContent>
 </xs:complexType>
  </xs:schema>
 </types>
         <message name="getThingWithParent-request"/>
         <message name="getThingWithParent-response">
                 <part name="result" element="types:ThingWithParent"/>
         </message>
 <portType name="moapserver-porttype">
  <operation name="getThingWithParent">
   <input name="getThingWithParent-request" message="tns:getThingWithParent-request"/>
   <output name="getThingWithParent-response" message="tns:getThingWithParent-response"/>
  </operation>
 </portType>
 <binding name="moapserver-binding" type="tns:moapserver-porttype">
  <moap:binding style="rpc"
   transport="http://schemas.xmlmoap.org/moap/http"/>
  <operation name="getThingWithParent">
   <moap:operation moapAction="urn:test.moapserver.moapServer#getThingWithParent"/>
   <input>
      <moap:body use="encoded"
namespace="urn:test.moapserver#"
encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
   </input>
   <output>
      <moap:body use="encoded"
namespace="urn:test.moapserver#"
encodingStyle="http://schemas.xmlmoap.org/moap/encoding/"/>
   </output>
  </operation>
 </binding>

 <service name="moapserver">
  <!-- @binding doesn't like to be tns: -->
  <port name="moapserver-port" binding="tns:moapserver-binding">
   <moap:address location="xxxxxxxxxxxx"/>
  </port>
 </service>

</definitions>
