<?xml version="1.0" encoding="UTF-8"?>
<definitions
		xmlns:http="http://schemas.xmlmoap.org/wsdl/http/"
		xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/"
		xmlns:s="http://www.w3.org/2001/XMLSchema"
		xmlns:s0="http://test.pl"
		targetNamespace="http://test.pl"
		xmlns="http://schemas.xmlmoap.org/wsdl/"
>
	<types>
		<s:schema elementFormDefault="qualified" targetNamespace="http://test.pl">
			<s:complexType name="Test">
				<s:attribute use="required" name="strA" type="s:string"/>
				<s:attribute use="required" name="strB" type="s:string"/>
			</s:complexType>
			<s:element type="s0:Test" name="Test"/>
			<s:element type="s:string" name="Ret"/>
		</s:schema>
	</types>

	<message name="TestmoapIn">
		<part name="parameters" element="s0:Test"/>
	</message>
	<message name="TestmoapOut">
		<part name="parameters" element="s0:Ret"/>
	</message>
	<portType name="Testmoap">
		<operation name="Test">
			<input message="s0:TestmoapIn"/>
			<output message="s0:TestmoapOut"/>
		</operation>
	</portType>
	<binding name="Testmoap" type="s0:Testmoap">
		<moap:binding transport="http://schemas.xmlmoap.org/moap/http"
style="document"/>
		<operation name="Test">
			<moap:operation moapAction="http:/Test/Test" style="document"/>
			<input>
				<moap:body use="literal"/>
			</input>
			<output>
				<moap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="Test">
		<port name="TestmoapPort" binding="s0:Testmoap">
			<moap:address location="http://localhost:8080/~dmitry/bug38004/server.php"/>
		</port>
	</service>
</definitions>
