<?xml version="1.0" ?>
<definitions
    xmlns:moap-ENV="http://schemas.xmlmoap.org/moap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:moap-ENC="http://schemas.xmlmoap.org/moap/encoding/"
    xmlns:si="http://moapinterop.org/xsd"
    xmlns:tns="http://linuxsrv.home/~dmitry/moap/test.wsdl"
    xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/"
    xmlns:wsdl="http://schemas.xmlmoap.org/wsdl/"
    xmlns="http://schemas.xmlmoap.org/wsdl/"
    targetNamespace="http://linuxsrv.home/~dmitry/moap/test.wsdl">

  <message name="echoLongRequest">
    <part name="x" type="xsd:long" />
  </message>

  <message name="echoLongResponse">
    <part name="x" type="xsd:long" />
  </message>

  <portType name="TestServicePortType">
    <operation name="echoLong">
      <input message="tns:echoLongRequest" />
      <output message="tns:echoLongResponse" />
    </operation>
  </portType>

  <binding name="TestServiceBinding" type="tns:TestServicePortType">
    <moap:binding style="rpc" transport="http://schemas.xmlmoap.org/moap/http" />
    <operation name="echoLong">
      <moap:operation style="rpc" />
      <input>
        <moap:body use="encoded" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/" />
      </input>
      <output>
        <moap:body use="encoded" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/" />
      </output>
    </operation>
  </binding>

  <service name="TestService">
    <port name="TestServicePort" binding="tns:TestServiceBinding">
      <moap:address location="test://" />
    </port>
  </service>

</definitions>
