<?xml version="1.0" encoding="UTF-8"?>
<definitions name="netDB"
        targetNamespace="urn:netDB"
        xmlns:typens="urn:netDB"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:moap="http://schemas.xmlmoap.org/wsdl/moap/"
        xmlns:moapenc="http://schemas.xmlmoap.org/moap/encoding/"
        xmlns:wsdl="http://schemas.xmlmoap.org/wsdl/"
        xmlns="http://schemas.xmlmoap.org/wsdl/">
	<message name="checkAuthIN">
		<part name="peid" type="xsd:integer" />
		<part name="auth" type="xsd:string" />
	</message>
	<message name="checkAuthOUT">
		<part name="peidx" type="xsd:integer" />
	</message>
	<portType name="netDB">
		<operation name="checkAuth">
			<input message="typens:checkAuthIN" />
			<output message="typens:checkAuthOUT" />
		</operation>
	</portType>
	<binding name="netDB" type="typens:netDB">
		<moap:binding type="rpc" transport="http://schemas.xmlmoap.org/moap/http" />
		<operation name="checkAuth">
			<moap:operation moapAction="urn:checkAuth" />
			<input>
				<moap:body use="encoded" namespace="urn:netDB" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/" />
			</input>
			<output>
				<moap:body use="encoded" namespace="urn:netDB" encodingStyle="http://schemas.xmlmoap.org/moap/encoding/" />
			</output>
		</operation>
	</binding>
	<service name="netDB">
		<port name="netDBPort" binding="typens:netDB">
			<moap:address location="http://netdb.alphawest.com.au/xml/moap/server.php"/>
		</port>
	</service>
</definitions>
